services:
  web-app:
    build: .
    container_name: web-app
    env_file: 
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  sqlite_data: